config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :users
  resources :comments
  resources :sessions
     # nest route
    resources :posts do
     resources :comments
   end


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete "/logout" => "sessions#destroy"
  get '/logout' => 'sessions#destroy'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :email, presence: true, length: {maximum: 30}
  validates :password, presence: true, length: {minimum: 5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    @posts = Post.all
  end

  def new
    @comment = Comment.new
    @post = Post.new
  end

  # def create
  #   user = User.find(session[:user_id])
  #
  #   @post = Post.find(params[:post_id])
  #   @comment = @post.comments.create(comment_params)
  #   puts @post
  #   if @comment.save
  #     flash[:notice] = "Comment successfully added"
  #     post.comments < @comment
  #     redirect_to post_path(@post)
  #   else
  #     flash[:alert] = "Error posting comment"
  #     redirect_to post_path(@post)
  #   end
  # end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    if @comment.destroy
      flash[:notice] = "Comment deleted"
      redirect_to post_path(@post)
    else
      flash[:alert] = "There was an issue deleting comment"
      redirect_to post_path(@post)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
   @posts = Post.all.order('created_at DESC')
  end
 # creates id
  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end
# creates the post
  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      redirect_to user_path(session[:user_id])
    else
     render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_path(session[:user_id])
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:content,:title)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

 end

 def create
   @user = User.where(email: params[:email]).first
   if @user && @user.password == params[:password]
     session[:user_id] = @user.id
     puts 'SessionStart'+'@'*45
     flash[:notice] = "Logged in"
     redirect_to root_path
   else
     puts 'X'*30
     flash[:alert] = "Incorrect email or password"
     redirect_to login_path
   end
 end

 def destroy
   session[:user_id] = nil
   puts 'SessionEnd'+'@'*45
   flash[:notice] = "Logged out successfully"
   redirect_to root_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You are now a Blogger Blogger!!."
      # redirect_to root_path
      redirect_to root_path
    else
      flash[:alert] = "There was a problem saving your account."
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    if @user.save
      flash[:notice] = "Your account was updated successfully."
      redirect_to users_path
    else
      flash[:alert] = "There was a problem updating your account."
      redirect_to edit_users_path
    end
  end


  def destroy
    puts 'HERE I AM'
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "User deleted successfully."
    else
      flash[:alert] = "An error occurred."
    end
    redirect_to users_path
  end


  private

  def user_params
    params.require(:user).permit(:email,:password,:fname,:lname,:age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<!-- <h2>Edit Comments</h2> -->


<%= form_for [@post, @comment] do |form| %>
  <br>
  <center><%= form.text_area :content, cols: 40, rows: 10, placeholder: "Edit a comment..." %>
  <br>
  <br>
  <%= form.submit ("Confirm") %>
  <%=link_to("Delete comment", post_comment_path(@post, @comment), method: :delete, data: {confirm: "Are you sure you want to delete this comment?"})%>
  </center>
<% end %>

app/views/comments/index.html.erb
<!-- <h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p> -->
<% @comment.each do |comment| %>
<%= comment.content %>
  <% if session[:user_id] == post.user_id%>
    <%= link_to("Edit", edit_post_comment_path(post)) %>
    <%= link_to("Delete", post_comment_path(comment), method: :delete, data: {confirm: "Are you sure you want to delete this comment?"})%>
  <% end %>

app/views/comments/new.html.erb
<!-- <h1>Comments#new</h1> -->


<h1><%= @post.content %></h1>
<center><%= form_for @comment, url: post_comments_path, method: :post do |form| %>
<br>
<%= form.text_area :content, cols: 40, rows: 10, placeholder: "Write a comment..." %>

<br>
<br>

<%= form.submit ("Post") %>
</center>
<br>
<% @post.comments.each do |comment|%>
<br>
<h4><%= User.find(comment.user_id).username %> said: <%= comment.content %></h4>
<%= link_to "Edit", edit_post_comment_path(@post, comment) %>
<% end %>
<% end %>

app/views/comments/show.html.erb
<!-- <h1>Comments#show</h1> -->
<p>Find me in app/views/comments/show.html.erb</p>

<%= @post.content%>

<%= form_for @comment, url: post_comments_path, method: :post do |form| %>
  <br>
  <%= form.text_area :content, placeholder: "Write a comment..." %>

  <br>
  <br>
  <br>

<ul>
  <% post.comments.each do |comment| %>
    <li><%= comment.content %></li>
  <%end%>
</ul>
<br>
</li>

app/views/home/index.html.erb
<!-- <h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p> -->

<h2>Thank you for signing up with BLOG! You are now part of the Blogger Blogger family.<h2>
  <h2>Now that you are registered, go ahead and BlogIn to post</h2>


<ul>
  <li>bläɡ/</li>
  <li>noun</li>
  <li>
  a regularly updated website or web page, typically one run by an individual or small group, that is written in an informal or conversational style.</li>
  <li>verb</li>
  <li>1.
  add new material to or regularly update a blog.
  "it's about a week since I last blogged"</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  </head>

  <body>

    <nav>
      <%= image_tag "blog_blog1.png" %>
      <div id="main_content">
       <div id="header">
        <% if session[:user_id] %> |
        <%= link_to "Feed", posts_path %> |
        <%= link_to "Create a Post", new_post_path %> |
        <%= link_to "Edit Profile", edit_user_path(session[:user_id]) %> |


        <%= link_to "Sign Out", session_path(session[:user_id]), method: :delete %> |

        <% else %>
        <%= link_to "Sign Up", new_user_path %> |
        <%= link_to "Blogin", new_session_path %> |
        <% end %>
      </div>
    </div>
      </nav>

         <div id="main_content">
          <div id="header">
           <p>Bloger Bloger</p>
            <div class="buttons">
              <!-- <!- click on button to create a new post -->

           </div>
         </div>

    <div id="main" class="container">
      <div class="flashNotice">
        <% if flash[:notice] %>
        <%= flash[:notice] %>
        <% end %>
      </div>
      <div class="flashAlert">
        <% if flash[:alert] %>
        <%= flash[:alert] %>
        <% end %>
      </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |form| %>
  <center><%= form.label :title, ("Edit Title") %></center>
  <center><%= form.text_field :title %></center>
  <br>
  <br>
  <center><%= form.label :content,("Edit Content") %></center>
  <center><%= form.text_area :content, cols: 50, rows: 15 %></center>
  <br>
  <br>
  <center><%= form.submit "enter" %></center>
<% end %>

<%= link_to "Edit", edit_post_path(post.id) %>  |
<%= link_to "Delete", post_path(post.id), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>

app/views/posts/index.html.erb
<!-- <h1>Posts#index</h1> -->
<!-- <p>Find me in app/views/posts/index.html.erb</p> -->

<ul>
  <% @posts.each do |post| %>
  <li>
    <strong>Title: <%= post.title %></strong>
    <br>
    <br>
    <%= post.content %>
    <br>
    <br>
    <br>
    <%= link_to "Comment Post", new_post_comment_path(post.id) %> |
    <br>
    <br>
    <br>
    <br>
  </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Blog Away!</h1>
<!-- <p>Find me in app/views/posts/new.html.erb</p> -->

<%= form_for Post.new do |form| %>
<%= form.label :Title %><br>
<%= form.text_field :title %><br><br>
<%= form.label :Post %><br><br>
<%= form.text_field :content %><br><br>
<%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<!-- <h1>Posts#show</h1> -->


<h2><%= @post.title %></h2>
<%= @post.content %>
<br>
<% @post.comments.each do |c|%>
  <br>
  <div>
    <%= User.find(c.user_id).username %> said: <%= c.content%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<div id="form-div3">
  <%= form_for @user do |form| %>
    <%= form.label :fname, ("Edit First Name") %>
    <%= form.text_field :fname %>
    <br>
    <br>
    <%= form.label :lname, ("Edit Last Name") %>
    <%= form.text_field :lname %>
    <br>
    <br>
    <%= form.label :Email, ("Edit Email") %>
    <%= form.text_field :email %>
    <br>
    <br>
    <%= form.label :password, ("Edit Password") %>
    <%= form.password_field :password %>
    <br>
    <br>
    <%= form.submit %>
    <br>
    <br>
    <%=link_to("Delete Profile", user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete your profile?"})%>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= link_to "Create User" ,"users/new", class:"body_link" %>

<div class="container">
  <h1 class="text-center">Users</h1>
  <div id="users_list">


    <% @user.each do |u| %>
    <%  if u.fname %>
    <%= link_to "#{u.fname} #{u.lname}", user_path(u), class: "body_link" %>
    <% else %>
    <%= link_to "Unknown", user_path(u) %>
    <% end %>
    <br>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<!-- <h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p> -->

<%= form_for User.new do |u| %>


<p><%= u.text_field :fname, placeholder: "First Name", class: "field", required: true %></p><br>
<p><%= u.text_field :lname, placeholder: "Last Name", class: "field", required: true %></p><br>
<p><%= u.email_field :email, placeholder: "EMAIL", class: "field", required: true  %></p><br>
<p><%= u.password_field :password, placeholder: "PASSWORD", class: "field", required: true %></p><br>
<p><%= u.submit value: "SUBMIT", class: "button" %><br>
 <% link_to new_post_path %></p>
<% end %>

app/views/users/show.html.erb
<!-- <h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p> -->

<div id="profile_name" class="focus-in-expand">

<%= @user.fname %> <%= @user.lname%></div><br>
<p><strong>Email: </strong><%= @user.email%></p>
<p><strong>User ID: </strong><%= @user.id %></p>


<%= link_to "Cancel Account", user_path(@user), method: :delete %>